language: python
os:
  - linux
  - windows
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install nose pylint
  - python setup.py install
script:
  - nosetests && pylint --errors-only pywiktionary
